repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12 # dernière version stabless
    hooks:
      - id: ruff
        args: ["--fix"] # applique le formatage automatiquement
